# ğŸ»â€â„ï¸ğŸ’ ume: Easy, self-hostable, and flexible image host made in Rust
# Copyright 2021-2025 Noel Towa <cutie@floofy.dev>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kubeVersion: ">=1.29"
description: "ğŸ»â€â„ï¸ğŸ’ Easy, and flexible image host to share with your friends on Discord, Telegram, and more."
apiVersion: v2
appVersion: "4.2.1"
version: 0.1.0
type: application
home: https://floofy.dev/oss/ume
name: ume
keywords:
  - image-server
  - ume
maintainers:
  - name: Noel Towa
    email: cutie@floofy.dev
    url: https://floofy.dev
annotations:
  charts.noelware.org/licenses: Apache-2.0
  charts.noelware.org/categories: Miscellaneous
dependencies:
  - name: common
    version: 2.31.3
    repository: oci://registry-1.docker.io/bitnamicharts
  - name: postgresql
    version: 16.7.21
    repository: oci://registry-1.docker.io/bitnamicharts
  - name: mongodb
    version: 16.5.33
    repository: oci://registry-1.docker.io/bitnamicharts
